module.exports = {
  "MONGO_DB" : "DB_URL",
  "LOCAL_SITES_PATH" : "LOCAL_SITES_PATH",
  "SITES_PATH" : "SITES_PATH",
  "SITES_CONF" : "SITES_CONF",
  "SITES_CONF_PATH" : "SITES_CONF_PATH",
  "TEMP_PATH" : "TEMP_PATH",
  "FETCHBOT_BIND" : "FETCHBOT_BIND",
  "FETCHBOT_PORT" : "FETCHBOT_PORT",
  "CONTENT_STATUSES" : {
    "NOT_DOWNLOADED" : "NOT_DOWNLOADED",
    "DOWNLOADED" : "DOWNLOADED",
    "EXTRACTED" : "EXTRACTED"
  } 
}